server.port=9191

# Stockage fichiers (Windows - chemin absolu)
app.storage-dir=C:/temp/pdfoffice/uploads

# Taille upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Afficher erreurs (dev)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
# =========================
# CloudConvert
# =========================
CLOUDCONVERT_API_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGU0OWJlM2RmYWFiOGQyOTY5NTliNTQyZTg4MjFkZGZiYTZiYjY3MmMzNTk5YjVlMGYyZmNmNmE5OTYzNmNjODMyYjY0N2IxYThhMzE0ZjQiLCJpYXQiOjE3Njk0NTE0MzkuODI4NDcyLCJuYmYiOjE3Njk0NTE0MzkuODI4NDczLCJleHAiOjQ5MjUxMjUwMzkuODIzNTYyLCJzdWIiOiI3NDA0ODEwOSIsInNjb3BlcyI6WyJ0YXNrLnJlYWQiLCJ0YXNrLndyaXRlIl19.oDs3hKq_V4m-7uxTXmF1PDda-l0bDwQCftLcpPUNVL2R4cBL7l6jmsyZuUdK6mSi95521h-fYkAvN-78XO74CZ3NbfW9LuWc0ABNS9VeeSyvi1muolxfqGy6I3LzGLHtvVdGThUxbxa_1dc8IOM-J_SEaPr2-BLk_HTp41dntYMYWthamLnAv4x03_J9vcLtNNqAlNOp-iM0ScAyGP0lKJsVsPjvSFNNUwUZzciVmqUlZACslfwnfeTuWg2xTH8lozHcA4rom6kqEyYKLKLX3zvwHoWs7vqNsYO11aBcfDnYXh3EV7lZCjm5G-zpl2p7hOvwQ5SN9JDAw7K4xuxfuXVSa0W28oeWS6amGjuYmJ_U_FYWG0HeKvd-SjoSkvlCzg63q-IdkqBRZVs1SuCmCHQGiDEJ2wJ2vx40xgKIWJzBV5J2Y2nri7XovlIH_Ex_D6nY7nWkUiy-D4MQE1MROpzI-1NjKJpVbH0HDVrPXs_G9RBDivjA4sR7ACOyRAmC8u8nBPy2ymxaIvwHvnKptGu-SZj6oP_sB2IERa-U4O_b7qoaTjSQpGmeTqrGgagPudmDwizpFucSf5Nr0dzrENzTn2wie1xJAOsyk_ro2Fzb9Z2FFsTxIbGR1EMLlJpLi6qZ1ljIi-tE0kBv_n3zTAM4CgBlgHyshVGOtdLPwPk
CLOUDCONVERT_SANDBOX=false
CLOUDCONVERT_WEBHOOK_SIGNING_SECRET=
